test_task:
  container:
    matrix:
      image: python:2.7
      image: python:3.5
      image: python:3.6
      image: python:3.7
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements-dev.txt
    populate_script: pip install -r requirements-dev.txt
  test_script: pytest && pylint examples ntelebot
